---
title: "Hypothesis_2_Analysis"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##Load data
```{r}
data = read.csv("EV_Reg_Indicators_By_State.csv")
head(data)
data = data[,which(!colnames(data) %in% c("State.Codes"))]
summary(data)
plot(data[, which(!colnames(data) %in% c("US.State"))])
data$Per.Capita.GDP = data$Gross.Domestic.Product..All.Industries/data$Population*10^5
colnames(data)

library(corrplot)
corrplot(cor(data[, c(1,7,3,4,5,6,8,9)]), type = "upper")
plot(data[,c(1,7,3,4,5,6,8,9)])
```

## Model Fitting

```{r}
#Per Capita GDP vs Sales by Population
# Log Transformation on response
# OUtlier detected for DC -> residual plot non-constant variance, normal dist
# Remove outlier -> constant variance, normal dist
fit1 = lm(log(Sales.by.Population) ~ Per.Capita.GDP, data = data[-8,])
plot(fit1)
boxCox(fit1)
summary(fit1)
```

```{r}

fit3 = lm(log(Sales.by.Population) ~ Per.Capita.Personal.Income, data = data)
plot(fit3)
boxCox(fit3)
plot(log(Sales.by.Population) ~ Per.Capita.Personal.Income, data = data)
abline(fit3)
summary(fit3)


fit3.log = glm(Sales.by.Population ~ Per.Capita.Personal.Income, data = data, family = poisson)
fit3.log$coefficients

x = 3700: 9000
y = exp(2.600348e+00 + (3.315661e-05*x))
plot(x,y)
plot(Sales.by.Population ~ Per.Capita.Personal.Income, data = data)
lines(x, y, col=4)

scatter.smooth(data$Sales.by.Population, exp(2.600348e+00 + (3.315661e-05*data$Per.Capita.Personal.Income)))

summary(fit3.log)
```

```{r}
fit.full = lm(log(Sales.by.Population)~ log(Unemployment.Rate) + Per.Capita.GDP + Per.Capita.Personal.Income, data = data)
plot(fit.full)
summary(fit.full)
vif(fit.full)
fit.partial = lm(log(Sales.by.Population)~  Per.Capita.GDP + Per.Capita.Personal.Income, data = data)
plot(fit.partial)
summary(fit.partial)

anova(fit3, fit.partial)
```

```{r}
fit.electricity = lm(log(Sales.by.Population)~ Per.Capita.Personal.Income + Electricity.Price, data = data)
plot(fit.electricity)
summary(fit.electricity)

fit.elec.only = lm(log(Sales.by.Population)~ Electricity.Price, data = data)
plot(fit.elec.only)
summary(fit.elec.only)

summary(fit3)

anova(fit.elec.only, fit.electricity)
anova(fit3, fit.electricity)
```

